# Generated by Django 5.0.6 on 2025-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(choices=[('Leads Manangement Application', 'Leads Manangement Application'), ('Music School Application', 'Music School Application'), ('Web Development', 'Web Development'), ('IT Customization', 'IT Customization'), ('IOT Customization', 'IOT Customization')], max_length=50),
        ),
    ]
